version: '3'

services:
  web:
    build:
      context: .
      args:
        http_proxy: ${BUILD_PROXY}
        https_proxy: ${BUILD_PROXY}
        HTTP_PROXY: ${BUILD_PROXY}
        HTTPS_PROXY: ${BUILD_PROXY}
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - bundle:/bundle
    ports:
      - "3000:3000"
    depends_on:
      - memcached
    stdin_open: true
    tty: true

  memcached:
    image: memcached:1.5

  # redis:
  #   image: redis:3.2

volumes:
  bundle:
